
⭐ 1) ماتریس چیست؟

ماتریس یک آرایهٔ مستطیلی از اعداد است که در سطرها و ستون‌ها قرار گرفته‌اند.
اگر ماتریسی ۳ سطر و ۲ ستون داشته باشد، می‌گوییم ابعاد آن ۳×۲ است.

انواع ماتریس

ماتریس مربعی: تعداد سطر = تعداد ستون.
این ماتریس‌ها ویژگی‌های خاصی مثل معکوس‌پذیری دارند.

ماتریس مستطیلی: سطر و ستون مساوی نیست.
معمولاً دیتاهای واقعی در ML مستطیلی هستند (سطر = نمونه، ستون = ویژگی).

مثال پایتونی:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])


اینجا A یک ماتریس ۲×۲ است.

⭐ 2) عملیات ماتریسی
🔹 الف) جمع و تفریق

فقط وقتی ممکن است که دو ماتریس هم‌ابعاد باشند.

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

A + B


خروجی:

[[ 6  8]
 [10 12]]


توضیح: عضوهای متناظر با هم جمع می‌شوند.

🔹 ب) ضرب ماتریسی

یکی از مهم‌ترین عملیات ریاضیات و یادگیری ماشین است.

قانون ضرب ماتریسی:

اگر A ابعاد m×n و B ابعاد n×p داشته باشد
حاصل ضرب ماتریس m×p خواهد بود.

یعنی تعداد ستون‌های ماتریس اول باید با سطرهای ماتریس دوم برابر باشد.

مثال پایتونی:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

A @ B


خروجی:

[[19 22]
 [43 50]]

توضیح:

این ضرب، ضرب ساده عضو به عضو نیست.
درواقع یک ترکیب خطی است که پایهٔ تمام تبدیلات ریاضی، شبکه‌های عصبی، PCA و… محسوب می‌شود.

⭐ 3) ماتریس معکوس

معکوس ماتریس A ماتریسی است به نام A⁻¹ که:

A × A⁻¹ = I
(ماتریس همانی)

نکته:

فقط ماتریس‌های مربعی ممکن است معکوس داشته باشند.

اگر دترمینان صفر باشد، معکوس وجود ندارد.

استفاده:

حل سیستم خطی Ax = b
وقتی A معکوس‌پذیر باشد:

x = A⁻¹ b

مثال پایتونی:
A = np.array([[1,2],[3,4]])
A_inv = np.linalg.inv(A)
A_inv


خروجی:

[[-2.   1. ]
 [ 1.5 -0.5]]


و بررسی همانی:

A @ A_inv


خروجی:

[[1. 0.]
 [0. 1.]]

⭐ 4) ماتریس‌های ویژه

(Eigenvalues & Eigenvectors)

این بخش کلیدی‌ترین قسمت برای اتصال مفاهیم به PCA است.

تعریف:

اگر A یک ماتریس مربعی باشد، و بردار v طوری باشد که:

A v = λ v

در این صورت:

v → بردار ویژه

λ → مقدار ویژه

معنی شهودی:

بردار ویژه، جهتی از فضا است که وقتی ماتریس روی آن عمل می‌کند:

جهت همان باقی می‌ماند

فقط بزرگ‌ یا کوچک می‌شود

و مقدار ویژه λ نشان می‌دهد مقدار تغییر مقیاس چقدر بوده.

مثال پایتونی:
A = np.array([[1,2],[3,4]])
eig_vals, eig_vecs = np.linalg.eig(A)

eig_vals, eig_vecs


خروجی معمولاً:

Eigenvalues: [-0.37228132  5.37228132]

Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


توضیح:

دو مقدار ویژه داریم؛ یکی کوچک‌تر، یکی بزرگ‌تر

هر ستون از ماتریس بردارهای ویژه یک جهت خاص را نشان می‌دهد

⭐ 5) کاربرد ماتریس‌های ویژه در PCA

PCA (تحلیل مؤلفه‌های اصلی) یک روش برای کاهش ابعاد دیتا است.
قدم‌های اصلی‌اش:

🔹 ۱) مرکزسازی داده

کم کردن میانگین از هر ستون.

X = np.array([
    [2,3],
    [3,5],
    [4,8]
])

X_centered = X - X.mean(axis=0)

🔹 ۲) ساخت ماتریس کوواریانس
cov = np.cov(X_centered.T)

🔹 ۳) محاسبه Eigenvalue و Eigenvector
eig_vals, eig_vecs = np.linalg.eig(cov)

🔹 ۴) انتخاب مؤلفه‌های اصلی

هر چه مقدار ویژه بزرگ‌تر باشد، آن جهت اطلاعات بیشتری از داده را نگه می‌دارد.

یعنی:

بزرگ‌ترین Eigenvalue → مؤلفه اصلی اول

بعدی → مؤلفه اصلی دوم

🔹 ۵) پروجکت کردن داده روی مؤلفه‌های اصلی

این کار باعث می‌شود داده از فضای مثلاً ۱۰ بُعدی به ۲ بُعد کاهش پیدا کند بدون اینکه اطلاعات مهم از دست برود.

⭐ جمع‌بندی

ماتریس‌ها ابزار پایه نمایش داده و انجام محاسبات هستند.

عملیات مهم آن‌ها: جمع، تفریق، ضرب، و معکوس.

بردارهای ویژه جهت‌های خاص ماتریس هستند.

PCA برای پیدا کردن مهم‌ترین جهت‌های داده از Eigenvalue و Eigenvector استفاده می‌کند.

تمام این مفاهیم با نمونه‌های NumPy دیدیم که دقیقاً در عمل چطور پیاده می‌شوند.